<a href="https://colab.research.google.com/github/NhiLehehe123/pursue_python/blob/main/python_for_HEP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
fruitdict = {
    "apples": "are red",
    "bananas": 2,
    "pears": [3,4,5],
}

fruitdict["apples"]

'are red'

In [4]:
for fruit in fruitdict:
  print(fruit, fruitdict[fruit])

apples are red
bananas 2
pears [3, 4, 5]


In [7]:
lst1 = [1, 2, 3, 4, 5]
lst2 = [5, 4, 3, 2, 1]

In [12]:
lst1[0:3] #0 inclusive to 3 inclusive

[1, 2, 3]

In [16]:
import numpy as np

arr1 = np.array(
    lst1
)

arr2 = np.array(
    lst2
)

In [17]:
%%timeit
# Slow way
sumrslt = []
for i, j in zip(arr1, arr2):
    sumrslt.append(i + j)

2.25 µs ± 457 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
print("Original:")
print(
    arr1
)
filter = [True, False, True, False, True]
print("Filtered using {}:".format(filter))
print(
    arr1[[True, False, True, False, True]]
)  # This will print only the elements of arr1 that are assigned the True value

Original:
[1 2 3 4 5]
Filtered using [True, False, True, False, True]:
[1 3 5]


In [32]:
sum = arr1 + arr2

sum6 = (sum > 6)
diff = (arr1 != arr2)
result = (sum6 | diff)
arr1[result]

array([1, 2, 4, 5])

In [33]:
filter1 = (arr1+arr2) > 6
filter2 = arr1 != arr2
arr1[filter1 | filter2]

array([1, 2, 4, 5])

In [35]:
lst3d = [[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]]
lst3d

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]],
 [[15, 16, 17, 18, 19], [20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]]

In [38]:
lst3d[0][1]

[5, 6, 7, 8, 9]

In [39]:
num_elems = 2 * 3 * 5
arr1d = np.arange(num_elems)
arr3d = arr1d.reshape(2, 3, 5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [46]:
arr3d[:,1:,1:]

array([[[ 6,  7,  8,  9],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [26, 27, 28, 29]]])

In [47]:
arr3d[0,:,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [52]:
filter3 = (arr3d == 1) | (arr3d == 7) | (arr3d == 13)
arr3d[filter3]

array([ 1,  7, 13])

In [53]:
# This will produce an error! Read the error message careful and try to understand it.
#np.array([
 #   [1, 2, 3],
  #  [1],
   # [5, 7, 8, 100]
#])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# Uproot I/O

In [63]:
!pip3 install scikit-hep-testdata

In [64]:
# Run this cell to import Uproot
import uproot
import skhep_testdata

# Downloads test file and returns path to it
filename = skhep_testdata.data_path("uproot-Event.root")
file = uproot.open(filename)
file

<ReadOnlyDirectory '/' at 0x7eabf0785b90>

In [65]:
file.items()

[('ProcessID0;1', <TProcessID (version 1) at 0x7eabf0ecad10>),
 ('htime;1', <TH1F (version 2) at 0x7eabefd67490>),
 ('T;1', <TTree 'T' (1 branches) at 0x7eabefd678d0>),
 ('hstat;1', <TH1F (version 2) at 0x7eabefc73690>)]

In [66]:
h = file ["hstat"]
h

<TH1F (version 2) at 0x7eabefc73690>